package server;

import game.datastructures.Identity;
import io.javalin.Javalin;
import io.javalin.http.Context;
import io.javalin.websocket.WsCloseContext;
import io.javalin.websocket.WsConnectContext;
import io.javalin.websocket.WsContext;
import io.javalin.websocket.WsMessageContext;

import org.eclipse.jetty.websocket.api.StatusCode;
import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import server.util.Lobby;

import java.io.*;
import java.net.URI;
import java.sql.*;

import java.text.SimpleDateFormat;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;


public class SecretHitlerServer {

    ////// Static Fields
    // <editor-fold desc="Static Fields">
    // TODO: Replace this with an environment variable or environment flag
    public static final int DEFAULT_PORT_NUMBER = 4040;

    // Passed to server
    public static final String PARAM_LOBBY = "lobby";
    public static final String PARAM_NAME = "name";
    public static final String PARAM_COMMAND = "command";
    public static final String PARAM_TARGET = "target";
    public static final String PARAM_VOTE = "vote";
    public static final String PARAM_VETO = "veto";
    public static final String PARAM_CHOICE = "choice"; // the index of the chosen policy.
    public static final String PARAM_ICON = "icon";
    // Identifies the browser behind a connection so a player who drops can be
    // recognised and handed their seat back. Generated by the client.
    public static final String PARAM_CLIENT_ID = "client-id";
    // Identifies a single command so the client can tell which one an "ok" is
    // answering. Optional: a client that does not send one gets a bare "ok".
    public static final String PARAM_REQUEST_ID = "request-id";

    // Passed to client
    // The type of the packet tells the client how to parse the contents.
    public static final String PARAM_PACKET_TYPE = "type";
    public static final String PACKET_INVESTIGATION = "investigation";
    public static final String PACKET_GAME_STATE = "game";
    public static final String PACKET_LOBBY = "lobby";
    public static final String PACKET_OK = "ok"; // general response packet sent after any successful command.
    public static final String PACKET_PONG = "pong"; // response to pings.

    public static final String PARAM_INVESTIGATION = "investigation";
    public static final String FASCIST = "FASCIST";
    public static final String LIBERAL = "LIBERAL";

    // These are the commands that can be passed via a websocket connection.
    public static final String COMMAND_PING = "ping";
    public static final String COMMAND_START_GAME = "start-game";
    public static final String COMMAND_GET_STATE = "get-state";
    public static final String COMMAND_SET_LOBBY_SIZE = "set-lobby-size";
    public static final String COMMAND_SELECT_ICON = "select-icon";
    public static final String COMMAND_NOMINATE_CHANCELLOR = "nominate-chancellor";
    public static final String COMMAND_REGISTER_VOTE = "register-vote";
    public static final String COMMAND_REGISTER_PRESIDENT_CHOICE = "register-president-choice";
    public static final String COMMAND_REGISTER_CHANCELLOR_CHOICE = "register-chancellor-choice";
    public static final String COMMAND_REGISTER_CHANCELLOR_VETO = "chancellor-veto";
    public static final String COMMAND_REGISTER_PRESIDENT_VETO = "president-veto";

    public static final String COMMAND_REGISTER_EXECUTION = "register-execution";
    public static final String COMMAND_REGISTER_SPECIAL_ELECTION = "register-special-election";
    public static final String COMMAND_GET_INVESTIGATION = "get-investigation";
    public static final String COMMAND_REGISTER_PEEK = "register-peek";

    public static final String COMMAND_END_TERM = "end-term";
    public static final String COMMAND_LEAVE_LOBBY = "leave-lobby";

    // Websocket close reasons. The client reads the part before the colon to tell
    // a refusal it should give up on from a blip it should retry.
    public static final String REJECT_BAD_REQUEST = "bad-request";
    public static final String REJECT_LOBBY_NOT_FOUND = "lobby-not-found";
    public static final String REJECT_NOT_IN_LOBBY = "not-in-lobby";
    public static final String CLOSE_LOBBY_TIMED_OUT = "lobby-timed-out";
    public static final String CLOSE_SERVER_ERROR = "server-error";

    private static final String CODE_CHARACTERS = "ABCDEFGHIJKLMNOPQRSTWXYZ"; // u,v characters can look ambiguous
    private static final int CODE_LENGTH = 4;

    private static final float UPDATE_FREQUENCY_SECONDS = 60;

    // Jetty closes a websocket that has been silent for its idle timeout. Long
    // stretches of a game are silent, so the server pings each connection to keep
    // it alive; a connection that stops answering those pings is genuinely gone and
    // is closed once the idle timeout elapses. The browser answers these pings from
    // its network stack, so a backgrounded tab stays connected.
    private static final long WEBSOCKET_IDLE_TIMEOUT_SECONDS = 90;
    private static final long WEBSOCKET_PING_INTERVAL_SECONDS = 25;
    // </editor-fold>

    ///// Private Fields
    // <editor-fold desc="Private Fields">

    transient private static ConcurrentHashMap<WsContext, Lobby> userToLobby = new ConcurrentHashMap<>();
    private static ConcurrentHashMap<String, Lobby> codeToLobby = new ConcurrentHashMap<>();

    private static final Logger logger = LoggerFactory.getLogger(SecretHitlerServer.class);

    transient private static boolean hasLobbyChanged;

    // </editor-fold>

    ////// Private Methods

    /**
     * Prints the current list of lobbies and their players.
     */
    private static void printLobbyStatus() {
        synchronized (codeToLobby) {
            logger.info("Lobbies (" + codeToLobby.mappingCount() + ") : " + codeToLobby.keySet());
            for (Map.Entry<String, Lobby> entry : codeToLobby.entrySet()) {
                logger.debug("Lobby " + entry.getKey() + ": " + entry.getValue().getUserNames());
            }
        }
    }

    private static int getHerokuAssignedPort() {
        String herokuPort = System.getenv("PORT");
        if (herokuPort != null) {
            return Integer.parseInt(herokuPort);
        }
        return DEFAULT_PORT_NUMBER;
    }

    public static void main(String[] args) {
        // On load, check the connected database to see if there's a stored state from
        // the server.
        loadDatabaseBackup();
        removeInactiveLobbies(); // immediately clean in case of redundant lobbies.

        // Only initialize Javalin communication after the database has been queried.
        Javalin serverApp = Javalin.create(config -> {
            // Jetty defaults to closing a websocket after 30s of silence, which
            // disconnects everyone whenever a game pauses for thought. Raise it and
            // rely on the server pings started in onWebsocketConnect to keep live
            // connections busy, so the timeout only fires on genuinely dead ones.
            config.jetty.wsFactoryConfig(
                    factory -> factory.setIdleTimeout(Duration.ofSeconds(WEBSOCKET_IDLE_TIMEOUT_SECONDS)));
            config.plugins.enableCors(cors -> {
                if (ApplicationConfig.DEBUG) {
                    cors.add(it -> {
                        it.anyHost();
                    });
                } else {
                    cors.add(it -> {
                        for (String origin : ApplicationConfig.getAllowedOrigins()) {
                            it.allowHost(origin);
                        }
                    });
                }
            });
        }).start(getHerokuAssignedPort());

        serverApp.get("/check-login", SecretHitlerServer::checkLogin); // Checks if a login is valid.
        serverApp.get("/new-lobby", SecretHitlerServer::createNewLobby); // Creates and returns the code for a new lobby
        serverApp.get("/ping", SecretHitlerServer::ping);

        serverApp.ws("/game", wsHandler -> {
            wsHandler.onConnect(SecretHitlerServer::onWebsocketConnect);
            wsHandler.onMessage(SecretHitlerServer::onWebSocketMessage);
            wsHandler.onClose(SecretHitlerServer::onWebSocketClose);
        });

        // Add hook for termination that backs up the lobbies to the database.
        Runtime.getRuntime().addShutdownHook(new Thread() {
            public void run() {
                logger.info("Attempting to back up lobby data.");
                storeDatabaseBackup();
                printLobbyStatus();
            }
        });

        // Add timer for periodic updates.
        int delayMs = 0;
        int periodMs = (int) (UPDATE_FREQUENCY_SECONDS * 1000.0f);
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                removeInactiveLobbies();
                if (!codeToLobby.isEmpty()) {
                    printLobbyStatus();
                }
                // If there are active lobbies, store a backup of the game.
                if (!codeToLobby.isEmpty() && hasLobbyChanged) {
                    storeDatabaseBackup();
                    hasLobbyChanged = false;
                }
            }
        }, delayMs, periodMs);
    }

    /**
     * Checks for and removes any lobbies that have timed out.
     * 
     * @effects For each lobby in the {@code codeToLobby} map, checks if the lobby
     *          has timed out.
     *          If so, closes all websockets associated with the lobby and removes
     *          them from the
     *          {@code userToLobby} map, then removes the lobby from the
     *          {@code codeToLobby} map.
     */
    private static void removeInactiveLobbies() {
        Set<String> removedLobbyCodes = new HashSet<>();
        int removedCount = 0;
        Iterator<Map.Entry<String, Lobby>> itr = codeToLobby.entrySet().iterator();
        while (itr.hasNext()) {
            Map.Entry<String, Lobby> entry = itr.next();
            Lobby lobby = entry.getValue();
            if (lobby.hasTimedOut()) {
                // Remove the websocket connections.
                for (WsContext ctx : lobby.getConnections()) {
                    closeConnection(ctx, StatusCode.NORMAL, CLOSE_LOBBY_TIMED_OUT, "The lobby has timed out.");
                    userToLobby.remove(ctx);
                }
                removedLobbyCodes.add(entry.getKey());
                removedCount++;
                itr.remove();
            }
        }
        if (removedCount > 0) {
            logger.info(String.format("Removed %d inactive lobbies: %s", removedCount, removedLobbyCodes));
            printLobbyStatus();
            hasLobbyChanged = true;
        }
    }

    /////// Database Handling
    // <editor-fold desc="Database Handling">

    /**
     * Attempts to get a connection to the PostGres database.
     * 
     * @return null if no connection could be made.
     *         otherwise, returns a {@code java.sql.Connection} object.
     */
    private static Connection getDatabaseConnection() {
        // Get credentials from database or (if debug flag is set) via manual input.
        Connection c;
        try {
            URI databaseUri;
            String envUri = ApplicationConfig.DATABASE_URI;
            if (envUri == null) {
                logger.error("Could not connect to database: No ENV_DATABASE_URL environment variable provided.");
                return null;
            }
            databaseUri = new URI(envUri);

            String username = databaseUri.getUserInfo().split(":")[0];
            String password = databaseUri.getUserInfo().split(":")[1];
            String dbUrl = "jdbc:postgresql://" + databaseUri.getHost() + ':' + databaseUri.getPort()
                    + databaseUri.getPath();

            Class.forName("org.postgresql.Driver");
            c = DriverManager.getConnection(dbUrl, username, password);
            logger.info("Successfully connected to database.");
            return c;
        } catch (Exception e) {
            // Print failures no matter what
            logger.error("Failed to connect to database.", e);
            return null;
        }
    }

    /**
     * Loads lobby data stored in the database (intended to be run on server wake).
     * 
     * @effects {@code codeToLobby} is set to the stored database
     */
    @SuppressWarnings("unchecked")
    private static void loadDatabaseBackup() {
        // Get connection to the Postgres Database and select the backup data.
        Connection c = getDatabaseConnection();
        if (c == null) {
            return;
        }
        Statement stmt = null;

        try {
            // Initialize table, just in case
            initializeDatabase(c);

            stmt = c.createStatement();
            ResultSet rs = stmt.executeQuery("select * from backup;");
            rs.next(); // Will fail if there are no entries in the table, which is fine.

            String timestamp = rs.getString("timestamp");
            int numAttempts = rs.getInt("attempts");
            byte[] lobbyBytes = rs.getBytes("lobby_bytes");
            logger.info("Loaded backup from " + timestamp + ".");
            rs.close();
            stmt.close();

            // Update the number of attempts that have been made, for debugging.
            stmt = c.createStatement();
            stmt.executeUpdate("UPDATE backup SET attempts = '" + (numAttempts + 1) + "';");
            stmt.close();
            c.close();

            // Deserialize the data and convert to lobbies.
            // (Use try-with-resources to ensure streams are closed even if an error
            // occurs.)
            try (
                    ByteArrayInputStream lobbyByteStream = new ByteArrayInputStream(lobbyBytes);
                    ObjectInputStream objectStream = new ObjectInputStream(lobbyByteStream)) {
                codeToLobby = (ConcurrentHashMap<String, Lobby>) objectStream.readObject();
                objectStream.close();
                logger.debug("Successfully parsed lobby data from the database.");
            } catch (Exception e) {
                logger.error("Failed to parse lobby data from stored backup.", e);
            }

        } catch (Exception e) {
            logger.error("Failed to retrieve lobby backups from the database.", e);
        }
        printLobbyStatus();
    }

    private static void storeDatabaseBackup() {
        ByteArrayOutputStream byteBuilder = new ByteArrayOutputStream();
        try {
            // Serialize the Lobby data.
            ObjectOutputStream objectOutputStream = new ObjectOutputStream(byteBuilder);
            objectOutputStream.writeObject(codeToLobby);
            objectOutputStream.flush();
            objectOutputStream.close();
            byteBuilder.flush();
            // No need to close bytebuilder (close has no effect)
        } catch (Exception e) {
            logger.error("Failed to serialize the Lobby data.", e);
            return;
        }
        byte[] lobbyData = byteBuilder.toByteArray();
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String timestamp = formatter.format(new Timestamp(System.currentTimeMillis()));
        int attempts = 0;

        Connection c = getDatabaseConnection();
        if (c == null) {
            return;
        }
        try {
            String queryStr = "INSERT INTO BACKUP (id, timestamp, attempts, lobby_bytes)" +
                    "VALUES (0, ?, ?, ?) " +
                    "ON CONFLICT (id) DO UPDATE " +
                    "SET timestamp = excluded.timestamp, " +
                    "attempts = excluded.attempts, " +
                    "lobby_bytes = excluded.lobby_bytes; ";
            PreparedStatement pstmt = c.prepareStatement(queryStr);
            int i = 1;
            pstmt.setString(i++, timestamp);
            pstmt.setInt(i++, attempts);
            pstmt.setBytes(i++, lobbyData);
            pstmt.executeUpdate();
            c.close();
        } catch (Exception e) {
            logger.error("Failed to store the Lobby data in the database.", e);
            return;
        }
        logger.debug("Successfully saved Lobby state to the database.");
    }

    /**
     * Initializes the database by adding the BACKUP table.
     * 
     * @param c the connection to the database.
     * @effects the Postgres SQL datbase has a new
     */
    private static void initializeDatabase(Connection c) throws SQLException {
        Statement stmt = c.createStatement();
        stmt.executeUpdate("create table if not exists backup " +
                "(id INT UNIQUE, timestamp TEXT, attempts INT, lobby_bytes BYTEA);");
        stmt.close();
    }

    // </editor-fold>

    /////// Get Requests
    // <editor-fold desc="Get Requests">

    /**
     * Pings the server (intended to wake the inactive server)
     * 
     * @param ctx the context of the login request
     * @effects Returns the message "OK" with status code 200.
     */
    public static void ping(Context ctx) {
        ctx.status(200);
        ctx.result("OK");
    }

    /**
     * Determines whether a login is valid.
     * 
     * @param ctx the context of the login request.
     * @requires the context must have the following parameters:
     *           {@code lobby}: the code of the lobby.
     *           {@code name}: the username of the user.
     *           {@code command}: the command
     * @effects Result status is one of the following:
     *          <p>
     *          - 400: if the {@code lobby} or {@code name} parameters are
     *          missing (or blank).
     *          <p>
     *          - 404: if there is no lobby with the given code
     *          <p>
     *          - 403: the username is invalid (there is already another user
     *          with that name in the lobby.)
     *          <p>
     *          - 488: the lobby is currently in a game.
     *          <p>
     *          - 489: the lobby is full.
     *          <p>
     *          - 200: Success. There is a lobby with the given name and the
     *          user can open a websocket connection with these login
     *          credentials.
     */
    public static void checkLogin(Context ctx) {
        String lobbyCode = ctx.queryParam(PARAM_LOBBY);
        String name = ctx.queryParam(PARAM_NAME);
        String clientId = ctx.queryParam(PARAM_CLIENT_ID);
        if (lobbyCode == null || name == null || name.isEmpty() || name.isBlank()) {
            ctx.status(400);
            ctx.result("Lobby and name must be specified.");
            return;
        }

        Lobby lobby = codeToLobby.get(lobbyCode);
        if (lobby == null) { // lobby does not exist
            ctx.status(404);
            ctx.result("No such lobby found.");
            return;
        }

        // Ask the lobby the same question the websocket connect will ask, so this
        // pre-flight check cannot turn away a player the websocket would have let
        // in (a returning player whose old connection has not been cleaned up yet).
        Lobby.JoinDecision decision;
        synchronized (lobby) {
            decision = lobby.evaluateJoin(name, clientId);
        }
        if (decision.isAllowed()) {
            ctx.status(200);
            ctx.result(decision.isReclaim() ? "Login request valid (rejoining)." : "Login request valid.");
            return;
        }

        ctx.status(statusCodeForRejection(decision.getReason()));
        ctx.result(decision.getMessage());
    }

    /**
     * Maps a {@code Lobby} rejection reason onto the HTTP status the login check
     * has always used for it.
     *
     * @param reason the machine-readable rejection reason.
     * @return the matching HTTP status code.
     */
    private static int statusCodeForRejection(String reason) {
        if (Lobby.REJECT_LOBBY_FULL.equals(reason)) {
            return 489;
        } else if (Lobby.REJECT_GAME_IN_PROGRESS.equals(reason)) {
            return 488;
        } else if (Lobby.REJECT_NAME_TAKEN.equals(reason)) {
            return 403;
        }
        return 400;
    }

    /**
     * Generates a new lobby and returns the access code.
     * 
     * @param ctx the HTTP get request context.
     */
    public static void createNewLobby(Context ctx) {
        removeInactiveLobbies();
        hasLobbyChanged = true;

        String newCode = generateCode();
        while (codeToLobby.containsKey(newCode)) {
            newCode = generateCode();
        }

        Lobby lobby = new Lobby();
        codeToLobby.put(newCode, lobby); // add a new lobby with the given code.

        ctx.status(200);
        ctx.result(newCode);
        logger.info("New lobby created: " + newCode);
        logger.info("Available lobbies: " + codeToLobby.keySet());
    }

    /**
     * Generates a random code.
     * 
     * @return a String code, with length specified by {@code this.CODE_LENGTH} and
     *         characters randomly
     *         chosen from {@code CODE_CHARACTERS}.
     */
    private static String generateCode() {
        StringBuilder builder = new StringBuilder();
        while (builder.length() < CODE_LENGTH) {
            int index = (int) (Math.random() * CODE_CHARACTERS.length());
            builder.append(CODE_CHARACTERS.charAt(index));
        }
        return builder.toString();
    }

    // </editor-fold>

    /////// Websocket Handling
    // <editor-fold desc="Websocket Handling">

    /**
     * Called when a websocket connects to the server.
     * 
     * @param ctx the WsConnectContext of the websocket.
     * @requires the context must have the following parameters:
     *           {@code lobby}: a String representing the lobby code.
     *           {@code name}: a String username.
     *           {@code client-id}: optional. Identifies the browser, letting a
     *           player who dropped be recognised and given their seat back.
     * @effects Connects the user to the lobby, or closes the session with a reason
     *          of {@code bad-request}, {@code lobby-not-found}, or whichever
     *          refusal {@code Lobby.evaluateJoin} gave. The reason is sent as the
     *          websocket close reason so the client knows whether reconnecting
     *          could ever succeed.
     */
    private static void onWebsocketConnect(WsConnectContext ctx) {
        // Sanitize user input
        String code = ctx.queryParam(PARAM_LOBBY);
        String name = ctx.queryParam(PARAM_NAME);
        String clientId = ctx.queryParam(PARAM_CLIENT_ID);

        if (code == null || name == null || name.isEmpty() || name.isBlank()) {
            logger.debug("FAILED (Lobby or name is empty/null)");
            closeConnection(ctx, StatusCode.PROTOCOL, REJECT_BAD_REQUEST, "Lobby and name must be specified.");
            return;
        }

        logger.debug("Attempting to connect user '" + name + "' to lobby '" + code + "': ");
        Lobby lobby = codeToLobby.get(code);
        if (lobby == null) { // the lobby does not exist.
            logger.debug("FAILED (The lobby does not exist)");
            closeConnection(ctx, StatusCode.PROTOCOL, REJECT_LOBBY_NOT_FOUND,
                    "The lobby '" + code + "' does not exist.");
            return;
        }

        synchronized (lobby) {
            Lobby.JoinDecision decision = lobby.evaluateJoin(name, clientId);
            if (!decision.isAllowed()) {
                logger.debug("FAILED (" + decision.getReason() + ")");
                closeConnection(ctx, StatusCode.PROTOCOL, decision.getReason(), decision.getMessage());
                return;
            }

            logger.debug(decision.isReclaim() ? "SUCCESS (rejoined)" : "SUCCESS");
            lobby.addUser(ctx, name, clientId);
            userToLobby.put(ctx, lobby); // keep track of which lobby this connection is in.
            lobby.resetTimeout();

            // Keep the connection busy so Jetty's idle timeout only fires on a
            // connection that has genuinely stopped answering. The browser replies to
            // these below the application, so a backgrounded tab stays connected even
            // though its timers are throttled.
            ctx.enableAutomaticPings(WEBSOCKET_PING_INTERVAL_SECONDS, TimeUnit.SECONDS, null);

            lobby.updateAllUsers();
        }
        hasLobbyChanged = true;
    }

    /**
     * Closes a websocket, telling the client why in a form it can act on.
     *
     * @param ctx     the connection to close.
     * @param status  the websocket status code to close with.
     * @param reason  a short machine-readable reason, which the client reads to
     *                decide whether reconnecting is worth trying.
     * @param message a human-readable explanation shown to the player.
     * @effects closes the session. Failures are swallowed: a socket that cannot be
     *          closed is already gone.
     */
    private static void closeConnection(WsContext ctx, int status, String reason, String message) {
        try {
            ctx.session.close(status, reason + ": " + message);
        } catch (Exception e) {
            logger.debug("Failed to close a websocket (" + reason + ").", e);
        }
    }

    /**
     * Parses a websocket message sent from the user.
     * 
     * @param ctx the WsMessageContext of the websocket.
     * @requires the context must have the following parameters:
     *           {@code lobby}: a String representing the lobby code.
     *           {@code name}: a String username. Cannot already exist in the given
     *           lobby.
     *           {@code command}: a String command.
     * @modifies this
     * @effects Ends the websocket command with code 400 if the specified lobby does
     *          not exist, the user is not allowed
     *          to make this action (usually because they are not a
     *          president/chancellor), if a required parameter is
     *          missing, or the command cannot be executed in this state.
     *          <p>
     *          Updates the game state according to the specified command and
     *          updates every other connected user
     *          with the new state.
     */
    private static void onWebSocketMessage(WsMessageContext ctx) {
        // Parse message to JSON object.
        JSONObject message = new JSONObject(ctx.message());

        if (message.getString(PARAM_LOBBY) == null
                || message.getString(PARAM_NAME) == null
                || message.getString(PARAM_COMMAND) == null) {
            logger.warn("Message request failed: missing a parameter.");
            closeConnection(ctx, StatusCode.PROTOCOL, REJECT_BAD_REQUEST, "A required parameter is missing.");
            return;
        }

        String name = message.getString(PARAM_NAME);
        String lobbyCode = message.getString(PARAM_LOBBY);

        String logMessage = "Received a message from user '" + name + "' in lobby '" + lobbyCode + "' ("
                + ctx.message() + "): ";

        Lobby lobby = codeToLobby.get(lobbyCode);
        if (lobby == null) {
            logger.debug(logMessage + " FAILED (Lobby requested does not exist)");
            closeConnection(ctx, StatusCode.PROTOCOL, REJECT_LOBBY_NOT_FOUND, "The lobby does not exist.");
            return;
        }

        synchronized (lobby) {
            if (!lobby.hasUser(ctx, name)) {
                // Usually a message that was already in flight when this connection
                // was replaced by a newer one from the same player.
                logger.debug(logMessage + " FAILED (Lobby does not have the user)");
                closeConnection(ctx, StatusCode.PROTOCOL, REJECT_NOT_IN_LOBBY,
                        "The user is not in the lobby " + lobbyCode + ".");
                return;
            }

            lobby.resetTimeout();

            boolean updateUsers = true; // this flag can be disabled by certain commands.
            boolean sendOKMessage = true;
            try {
                switch (message.getString(PARAM_COMMAND)) {
                    case COMMAND_PING:
                        sendOKMessage = false;
                        updateUsers = false;
                        JSONObject msg = new JSONObject();
                        msg.put(PARAM_PACKET_TYPE, PACKET_PONG);
                        ctx.send(msg.toString());
                        break;

                    case COMMAND_START_GAME: // Starts the game.
                        lobby.startNewGame();
                        break;

                    case COMMAND_GET_STATE: // Requests the updated state of the game.
                        // No "ok" for this one: it is a read, answered by the
                        // state packet itself. Acknowledging it as well would put
                        // an "ok" on the wire that the player never asked for.
                        sendOKMessage = false;
                        lobby.updateUser(ctx, name);
                        break;

                    case COMMAND_NOMINATE_CHANCELLOR: // params: PARAM_TARGET (String)
                        verifyIsPresident(name, lobby);
                        lobby.game().nominateChancellor(message.getString(PARAM_TARGET));
                        break;

                    case COMMAND_REGISTER_VOTE: // params: PARAM_VOTE (boolean)
                        boolean vote = message.getBoolean(PARAM_VOTE);
                        lobby.game().registerVote(name, vote);
                        break;

                    case COMMAND_REGISTER_PRESIDENT_CHOICE: // params: PARAM_CHOICE (int)
                        verifyIsPresident(name, lobby);
                        int discard = message.getInt(PARAM_CHOICE);
                        lobby.game().presidentDiscardPolicy(discard);
                        break;

                    case COMMAND_REGISTER_CHANCELLOR_CHOICE: // params: PARAM_CHOICE (int)
                        verifyIsChancellor(name, lobby);
                        int enact = message.getInt(PARAM_CHOICE);
                        lobby.game().chancellorEnactPolicy(enact);
                        break;

                    case COMMAND_REGISTER_CHANCELLOR_VETO:
                        verifyIsChancellor(name, lobby);
                        lobby.game().chancellorVeto();
                        break;

                    case COMMAND_REGISTER_PRESIDENT_VETO: // params: PARAM_VETO (boolean)
                        verifyIsPresident(name, lobby);
                        boolean veto = message.getBoolean(PARAM_VETO);
                        lobby.game().presidentialVeto(veto);
                        break;

                    case COMMAND_REGISTER_EXECUTION: // params: PARAM_TARGET (String)
                        verifyIsPresident(name, lobby);
                        lobby.game().executePlayer(message.getString(PARAM_TARGET));
                        break;

                    case COMMAND_REGISTER_SPECIAL_ELECTION: // params: PARAM_TARGET (String)
                        verifyIsPresident(name, lobby);
                        lobby.game().electNextPresident(message.getString(PARAM_TARGET));
                        break;

                    case COMMAND_GET_INVESTIGATION: // params: PARAM_TARGET (String)
                        verifyIsPresident(name, lobby);
                        Identity id = lobby.game().investigatePlayer(message.getString(PARAM_TARGET));
                        // Construct and send a JSONObject.
                        JSONObject obj = new JSONObject();
                        obj.put(PARAM_PACKET_TYPE, PACKET_INVESTIGATION);
                        if (id == Identity.FASCIST) {
                            obj.put(PARAM_INVESTIGATION, FASCIST);
                        } else {
                            obj.put(PARAM_INVESTIGATION, LIBERAL);
                        }
                        obj.put(PARAM_TARGET, message.getString(PARAM_TARGET));
                        ctx.send(obj.toString());
                        break;

                    case COMMAND_REGISTER_PEEK:
                        verifyIsPresident(name, lobby);
                        lobby.game().endPeek();
                        break;

                    case COMMAND_END_TERM:
                        verifyIsPresident(name, lobby);
                        lobby.game().endPresidentialTerm();
                        break;

                    case COMMAND_SELECT_ICON:
                        String iconId = message.getString(PARAM_ICON);
                        lobby.trySetUserIcon(iconId, ctx);
                        break;

                    case COMMAND_LEAVE_LOBBY:
                        // A deliberate exit, as opposed to dropping off: free the seat
                        // straight away instead of holding it open for a reconnect.
                        sendOKMessage = false;
                        lobby.removeUserImmediately(ctx);
                        userToLobby.remove(ctx);
                        break;

                    default: // This is an invalid command.
                        throw new RuntimeException("unrecognized command " + message.get(PARAM_COMMAND));
                } // End switch

                if (sendOKMessage) {
                    logger.debug(logMessage + " SUCCESS");
                    JSONObject msg = new JSONObject();
                    msg.put(PARAM_PACKET_TYPE, PACKET_OK);
                    // Name the command being acknowledged, so the client can act
                    // on the answer to the command it is actually waiting on
                    // rather than on whichever "ok" happens to arrive first.
                    if (message.has(PARAM_REQUEST_ID)) {
                        msg.put(PARAM_REQUEST_ID, message.get(PARAM_REQUEST_ID));
                    }
                    ctx.send(msg.toString());
                }

            } catch (NullPointerException e) {
                // Show error messages by default, since they indicate API access
                // issues.
                logger.error(logMessage + " FAILED", e);
                closeConnection(ctx, StatusCode.PROTOCOL, CLOSE_SERVER_ERROR, "NullPointerException:" + e.toString());
            } catch (RuntimeException e) {
                logger.error(logMessage + " FAILED", e);
                closeConnection(ctx, StatusCode.PROTOCOL, CLOSE_SERVER_ERROR, "RuntimeException:" + e.toString());
            }
            if (updateUsers) {
                lobby.updateAllUsers();
            }
        }
        hasLobbyChanged = true;
    }

    // TODO: This is bad. This is bad code practice. Exceptions should not be
    // used for control flow.

    /**
     * Verifies that the user is the president.
     * 
     * @param name  String name of the user.
     * @param lobby the Lobby that the game is in.
     * @throws RuntimeException if the user is not the president.
     */
    private static void verifyIsPresident(String name, Lobby lobby) {
        if (!lobby.game().getCurrentPresident().equals(name)) {
            throw new RuntimeException("The player '" + name + "' is not currently president.");
        }
    }

    /**
     * Verifies that the user is the chancellor.
     * 
     * @param name  String name of the user.
     * @param lobby the Lobby that the game is in.
     * @throws RuntimeException if the user is not the chancellor.
     */
    private static void verifyIsChancellor(String name, Lobby lobby) {
        if (!lobby.game().getCurrentChancellor().equals(name)) {
            throw new RuntimeException("The player '" + name + "' is not currently chancellor.");
        }
    }

    /**
     * Called when a websocket is closed.
     * 
     * @param ctx the WsContext of the websocket.
     * @modifies this
     * @effects Removes the user from any connected lobbies.
     */
    private static void onWebSocketClose(WsCloseContext ctx) {
        if (userToLobby.containsKey(ctx)) {
            Lobby lobby = userToLobby.get(ctx);
            synchronized (lobby) {
                if (lobby.hasUser(ctx)) {
                    lobby.removeUser(ctx);
                    lobby.updateAllUsers();
                }
            }
            userToLobby.remove(ctx);
        }
    }

    // </editor-fold>

}
