package server.util;

import game.SecretHitlerGame;
import io.javalin.websocket.WsContext;
import org.eclipse.jetty.websocket.api.StatusCode;
import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import server.SecretHitlerServer;

import java.io.IOException;
import java.io.Serializable;
import java.util.*;
import java.util.Map.Entry;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.ConcurrentSkipListSet;
import java.util.stream.Collectors;

/**
 * A Lobby holds a collection of websocket connections, each representing a
 * player.
 * It maintains the game that the connections are associated with.
 *
 * A user is defined as an active websocket connection.
 */
public class Lobby implements Serializable {

    private static final long serialVersionUID = 1L;

    /* Reasons a connection can be turned away. These are sent to the client as
     * the websocket close reason so it can tell a temporary network blip (worth
     * retrying) apart from a permanent refusal (stop and tell the player). */
    public static final String REJECT_NAME_TAKEN = "name-taken";
    public static final String REJECT_LOBBY_FULL = "lobby-full";
    public static final String REJECT_GAME_IN_PROGRESS = "game-in-progress";

    /* Sent to a connection that has been superseded by a newer one from the same
     * browser. That client must not reconnect, or the two sockets fight forever. */
    public static final String CLOSE_REPLACED = "replaced";

    private SecretHitlerGame game;

    // These two marked transient because they track currently active/connected
    // users.
    transient private ConcurrentHashMap<WsContext, String> userToUsername;
    transient private Queue<String> activeUsernames;

    final private Set<String> usersInGame;
    final private ConcurrentHashMap<String, String> usernameToIcon;

    /* Used to reassign users to previously chosen images if they disconnect */
    final private ConcurrentHashMap<String, String> usernameToPreferredIcon;

    /* Which browser holds each seat. A client id is generated by the browser and
     * kept for the life of the tab, so a player that drops and comes back can be
     * recognised as the same person and handed their seat back, even when the
     * server has not yet noticed that their old socket is gone. Persisted with the
     * lobby so seats survive a server restart. */
    private ConcurrentHashMap<String, String> usernameToClientId;

    public static long LOBBY_TIMEOUT_DURATION_IN_MIN = 10;
    /* How long a seat (and its icon) is held for a player whose connection dropped.
     * Long enough to cover a phone locking or the player switching apps. */
    public static float PLAYER_TIMEOUT_IN_SEC = 20;
    private long timeout;

    private static Logger logger = LoggerFactory.getLogger(Lobby.class);

    private static int MAX_TIMER_SCHEDULING_ATTEMPTS = 2;
    transient private Timer userTimeoutTimer = new Timer();

    static String DEFAULT_ICON = "p_default";

    /**
     * Constructs a new Lobby.
     */
    public Lobby() {
        userToUsername = new ConcurrentHashMap<WsContext, String>();
        activeUsernames = new ConcurrentLinkedQueue<>();
        usersInGame = new ConcurrentSkipListSet<>();
        usernameToIcon = new ConcurrentHashMap<>();
        usernameToPreferredIcon = new ConcurrentHashMap<>();
        usernameToClientId = new ConcurrentHashMap<>();
        resetTimeout();
    }

    /**
     * Resets the internal timeout for this lobby.
     * 
     * @effects The lobby will time out in {@code TIMEOUT_DURATION_MS} ms from now.
     */
    synchronized public void resetTimeout() {
        // The timeout duration for the server. (currently 30 minutes)
        long MS_PER_MINUTE = 1000 * 60;
        timeout = System.currentTimeMillis() + MS_PER_MINUTE * LOBBY_TIMEOUT_DURATION_IN_MIN;
    }

    /**
     * Returns whether the lobby has timed out.
     * 
     * @return true if the Lobby has timed out.
     */
    synchronized public boolean hasTimedOut() {
        return timeout <= System.currentTimeMillis();
    }

    /**
     * Returns the set of websocket connections connected to this Lobby.
     * 
     * @return a set of WsContexts, where each context is a user connected to the
     *         Lobby.
     */
    synchronized public Set<WsContext> getConnections() {
        return userToUsername.keySet();
    }

    /**
     * Returns the list of usernames currently in the lobby or game.
     */
    synchronized public List<String> getUserNames() {
        if (game != null) {
            return game.getPlayerList().stream().map(player -> player.getUsername()).collect(Collectors.toList());
        } else {
            return new ArrayList<String>(userToUsername.values());
        }
    }

    /////// User Management
    // <editor-fold desc="User Management">

    /**
     * Returns whether the given user (websocket connection) is in this lobby
     * 
     * @param context the Websocket context of a user.
     * @return true iff the {@code context} is in this lobby.
     */
    synchronized public boolean hasUser(WsContext context) {
        return userToUsername.containsKey(context);
    }

    /**
     * Returns whether a user with the given name exists in this lobby.
     * 
     * @param context the Websocket context of the user.
     * @param name    the name of the user.
     * @return true iff {@code context} is a user in the lobby with the name
     *         {@code name}.
     */
    synchronized public boolean hasUser(WsContext context, String name) {
        return userToUsername.containsKey(context) && userToUsername.get(context).equals(name);
    }

    /**
     * Returns true if the lobby has a user with a given username.
     * 
     * @param name the username to check the Lobby for.
     * @return true iff the username {@code name} is in this lobby.
     */
    synchronized public boolean hasUserWithName(String name) {
        return userToUsername.values().contains(name);
    }

    /**
     * Checks if a user can be added back to the lobby while a game is running.
     * 
     * @param name the name of the user to add.
     * @return true if the user can be added. A user can only be added back if they
     *         are a player in the current game and no live connection is already
     *         playing as them.
     *
     *         Note that this deliberately does not consult
     *         {@code activeUsernames}: a seat is held there for
     *         {@code PLAYER_TIMEOUT_IN_SEC} after a player drops, and refusing them
     *         during that window is exactly what stops a player from rejoining
     *         straight after a blip.
     */
    synchronized public boolean canAddUserDuringGame(String name) {
        return usersInGame.contains(name) && !hasUserWithName(name);
    }

    /**
     * Drops any connections whose session has already been closed.
     *
     * @modifies this
     * @effects removes from the lobby every connection that is no longer open. A
     *          socket that dies without a close handshake (a phone going to sleep,
     *          a laptop changing networks) otherwise sits in the map holding a
     *          username hostage until Jetty's idle timeout notices.
     */
    synchronized private void pruneDeadConnections() {
        Iterator<Entry<WsContext, String>> itr = userToUsername.entrySet().iterator();
        while (itr.hasNext()) {
            Entry<WsContext, String> entry = itr.next();
            if (!entry.getKey().session.isOpen()) {
                logger.debug("Pruning the dead connection of '" + entry.getValue() + "'.");
                itr.remove();
            }
        }
    }

    /**
     * Returns whether {@code clientId} is the browser that owns the seat
     * {@code name}.
     *
     * @param name     the username of the seat.
     * @param clientId the id reported by the connecting browser, which may be null
     *                 for a client that predates client ids.
     * @return true iff the seat is known and belongs to this browser.
     */
    synchronized private boolean ownsSeat(String name, String clientId) {
        return clientId != null && !clientId.isEmpty() && clientId.equals(usernameToClientId.get(name));
    }

    /**
     * Thrown when a game cannot be started yet, for a reason the player can do
     * something about -- too few players, or a game already running.
     * <p>
     * Distinct from the RuntimeExceptions the command handler treats as protocol
     * violations: those hang up on the client, which would throw the host out of
     * their own lobby for asking too early.
     */
    public static class StartRefusedException extends RuntimeException {
        private static final long serialVersionUID = 1L;

        public StartRefusedException(String message) {
            super(message);
        }
    }

    /**
     * The verdict on a connection request: whether it may join, and if not, why.
     */
    public static class JoinDecision {
        private final boolean allowed;
        private final boolean reclaim;
        private final String reason;
        private final String message;

        private JoinDecision(boolean allowed, boolean reclaim, String reason, String message) {
            this.allowed = allowed;
            this.reclaim = reclaim;
            this.reason = reason;
            this.message = message;
        }

        static JoinDecision allow(boolean reclaim) {
            return new JoinDecision(true, reclaim, null, null);
        }

        static JoinDecision reject(String reason, String message) {
            return new JoinDecision(false, false, reason, message);
        }

        public boolean isAllowed() {
            return allowed;
        }

        /** True if this connection is taking back a seat it already held. */
        public boolean isReclaim() {
            return reclaim;
        }

        /** A short machine-readable reason for a refusal, or null if allowed. */
        public String getReason() {
            return reason;
        }

        /** A human-readable explanation of a refusal, or null if allowed. */
        public String getMessage() {
            return message;
        }
    }

    /**
     * Decides whether a connection identifying itself as {@code name} may join.
     * 
     * @param name     the username the connection wants to play as.
     * @param clientId the browser's client id, or null if it did not send one.
     * @modifies this
     * @effects prunes any connections that have already died, then returns the
     *          verdict. A player is let back in if the seat is still theirs: either
     *          because their browser owns it, or because the seat is held open for
     *          them and nobody else is using it.
     */
    synchronized public JoinDecision evaluateJoin(String name, String clientId) {
        pruneDeadConnections();

        if (hasUserWithName(name)) {
            // A live connection is already playing as this name. Only the browser
            // that owns the seat may take it over, which is how a reconnect gets
            // through before the server has noticed the old socket is gone.
            if (ownsSeat(name, clientId)) {
                return JoinDecision.allow(true);
            }
            return JoinDecision.reject(REJECT_NAME_TAKEN,
                    "There is already a user with the name '" + name + "' in the lobby.");
        }

        if (isInGame()) {
            if (canAddUserDuringGame(name)) {
                return JoinDecision.allow(true);
            }
            return JoinDecision.reject(REJECT_GAME_IN_PROGRESS, "The lobby is currently in a game.");
        }

        // The seat is still being held open after a drop, so taking it back costs
        // the lobby nothing and cannot push it over the player limit.
        if (activeUsernames.contains(name)) {
            return JoinDecision.allow(true);
        }

        if (isFull()) {
            return JoinDecision.reject(REJECT_LOBBY_FULL, "The lobby is currently full.");
        }
        return JoinDecision.allow(false);
    }

    /**
     * Closes and forgets every connection currently playing as {@code name}.
     * 
     * @param name the username whose connections should be dropped.
     * @modifies this
     * @effects removes the connections from the lobby and closes them with the
     *          {@code CLOSE_REPLACED} reason, which tells that client not to try to
     *          reconnect.
     */
    synchronized private void evictConnectionsFor(String name) {
        Iterator<Entry<WsContext, String>> itr = userToUsername.entrySet().iterator();
        while (itr.hasNext()) {
            Entry<WsContext, String> entry = itr.next();
            if (!entry.getValue().equals(name)) {
                continue;
            }
            WsContext stale = entry.getKey();
            // Remove it first: closing fires the close handler on another thread,
            // and it must not find this connection still holding the seat.
            itr.remove();
            try {
                stale.session.close(StatusCode.NORMAL, CLOSE_REPLACED);
            } catch (Exception e) {
                logger.debug("Failed to close the replaced connection of '" + name + "'.", e);
            }
        }
    }

    /**
     * Checks whether the lobby is full.
     * 
     * @return Returns true if the number of players in the lobby is {@literal >= }
     *         {@code SecretHitlerGame.MAX_PLAYERS}.
     */
    synchronized public boolean isFull() {
        return activeUsernames.size() >= SecretHitlerGame.MAX_PLAYERS;
    }

    /**
     * Adds a user (websocket connection) to the lobby.
     * 
     * @param context  the websocket connection context.
     * @param name     the name of the player to be added.
     * @param clientId the connecting browser's client id, or null if it did not
     *                 send one.
     * @throws IllegalArgumentException if a duplicate websocket is added, or if
     *                                  {@code evaluateJoin} would have refused this
     *                                  connection.
     * @modifies this
     * @effects adds the given user to the lobby, taking over the seat from any
     *          connection that still holds the same name, and records the browser
     *          as the owner of the seat so it can be recognised on a later
     *          reconnect. The player keeps the icon they had chosen.
     */
    synchronized public void addUser(WsContext context, String name, String clientId) {
        if (userToUsername.containsKey(context)) {
            throw new IllegalArgumentException("Duplicate websockets cannot be added to a lobby.");
        }
        JoinDecision decision = evaluateJoin(name, clientId);
        if (!decision.isAllowed()) {
            throw new IllegalArgumentException(decision.getMessage());
        }

        // Anything still connected under this name has been superseded.
        evictConnectionsFor(name);

        userToUsername.put(context, name);
        if (!activeUsernames.contains(name)) {
            activeUsernames.add(name);
        }
        if (clientId != null && !clientId.isEmpty()) {
            usernameToClientId.put(name, clientId);
        }

        // Only fall back to the default for a player who has never had an icon:
        // resetting it on every reconnect makes the icon picker pop up again and
        // briefly blocks the lobby from starting.
        if (!usernameToIcon.containsKey(name)) {
            usernameToIcon.put(name, DEFAULT_ICON);
        }
        if (usernameToPreferredIcon.containsKey(name)) {
            trySetUserIcon(usernameToPreferredIcon.get(name), context);
        }
    }

    /**
     * Removes a user from the lobby immediately, without holding their seat.
     * 
     * @param context the websocket connection of the player leaving.
     * @modifies this
     * @effects frees the player's seat, icon and seat ownership right away. Used
     *          when a player deliberately leaves, as opposed to dropping off, so
     *          the rest of the lobby does not have to wait out the reconnect grace
     *          period before starting.
     */
    synchronized public void removeUserImmediately(WsContext context) {
        if (!hasUser(context)) {
            return;
        }
        String username = userToUsername.remove(context);
        activeUsernames.remove(username);
        usernameToIcon.remove(username);
        usernameToClientId.remove(username);
    }

    /**
     * Removes a user from the Lobby.
     * 
     * @param context the websocket connection context of the player to remove.
     * @throws IllegalArgumentException if {@code context} is not a user in the
     *                                  Lobby.
     * @modifies this
     * @effects removes the user context (websocket connection) of the player from
     *          the lobby.
     */
    synchronized public void removeUser(WsContext context) {
        if (!hasUser(context)) {
            throw new IllegalArgumentException("Cannot remove a websocket that is not in the Lobby.");
        } else {
            // Delay removing players from the list by adding it to a timer.
            int delay_in_ms = (int) (PLAYER_TIMEOUT_IN_SEC * 1000);
            final String username = userToUsername.get(context);

            int timerSchedulingAttempts = 0;
            while (timerSchedulingAttempts < MAX_TIMER_SCHEDULING_ATTEMPTS) {
                try {
                    userTimeoutTimer.schedule(new RemoveUserTask(username), delay_in_ms);
                    break; // exit loop if successful
                } catch (IllegalStateException e) {
                    // Timer hit an error state and must be reset.
                    userTimeoutTimer.cancel();
                    userTimeoutTimer = new Timer();
                    timerSchedulingAttempts++;
                }
            }
            if (timerSchedulingAttempts == MAX_TIMER_SCHEDULING_ATTEMPTS) {
                System.out.println("Failed to schedule removal of the user '" + username + "'.");
            }

            userToUsername.remove(context);
        }
    }

    /**
     * Small helper class for removing users from the active users queue.
     */
    class RemoveUserTask extends TimerTask {
        private final String username;

        RemoveUserTask(String username) {
            this.username = username;
        }

        public void run() {
            synchronized (Lobby.this) {
                // If the user reconnected in the meantime, or their seat has already
                // been released, there is nothing to do.
                if (userToUsername.values().contains(username) || !activeUsernames.contains(username)) {
                    return;
                }
                activeUsernames.remove(username);

                if (!isInGame()) {
                    // The seat is gone, so let go of the icon and of the browser that
                    // owned it. During a game the seat is kept for the whole game, so
                    // the player keeps both and can rejoin as themselves.
                    usernameToIcon.remove(username); // possible for users to disconnect before choosing icon
                    usernameToClientId.remove(username);
                }
                updateAllUsers();
            }
        }
    }

    /**
     * Returns the number of active users connected to the Lobby.
     * 
     * @return the number of active websocket connections currently in the lobby.
     */
    synchronized public int getUserCount() {
        return activeUsernames.size();
    }

    /**
     * Sends a message to every connected user with the current game state.
     * 
     * @effects a message containing a JSONObject representing the state of the
     *          SecretHitlerGame is sent
     *          to each connected WsContext.
     *          ({@code GameToJSONConverter.convert()})
     */
    synchronized public void updateAllUsers() {
        for (Entry<WsContext, String> entry : new ArrayList<>(userToUsername.entrySet())) {
            updateUser(entry.getKey(), entry.getValue());
        }

        // Check if the game ended.
        if (game != null && game.hasGameFinished()) {
            game = null;
        }
    }

    /**
     * Sends a message to the specified user with the current game state.
     * 
     * @param ctx the WsContext websocket context.
     * @effects a message containing a JSONObject representing the state of the
     *          SecretHitlerGame is sent
     *          to the specified WsContext. ({@code GameToJSONConverter.convert()})
     */
    synchronized public void updateUser(WsContext ctx, String userName) {
        JSONObject message;
        if (isInGame()) {
            message = GameToJSONConverter.convert(game, userName); // sends the game state
            message.put(SecretHitlerServer.PARAM_PACKET_TYPE, SecretHitlerServer.PACKET_GAME_STATE);
        } else {
            message = new JSONObject();
            message.put(SecretHitlerServer.PARAM_PACKET_TYPE, SecretHitlerServer.PACKET_LOBBY);
            message.put("usernames", activeUsernames.toArray());
        }
        // Add user icons to the update message
        JSONObject icons = new JSONObject(usernameToIcon);
        message.put("icon", icons);

        try {
            ctx.send(message.toString());
        } catch (Exception e) {
            // The socket died between the last check and this send. Drop it here so
            // one player's dead connection cannot stop everyone else being updated;
            // the close handler tidies up the rest.
            logger.debug("Failed to send an update to '" + userName + "'; dropping the connection.", e);
            userToUsername.remove(ctx);
        }
    }

    /**
     * Called when an object is deserialized (see Serializable in Java docs).
     * Initializes the userToUsername and activeUsernames, as they are transient
     * objects and not saved during
     * serialization of Lobby.
     * 
     * @param in the Object Input Stream that is reading in the object.
     * @throws IOException
     * @throws ClassNotFoundException
     */
    private void readObject(java.io.ObjectInputStream in) throws IOException, ClassNotFoundException {
        in.defaultReadObject();
        userToUsername = new ConcurrentHashMap<>();
        activeUsernames = new ConcurrentLinkedQueue<>();
        userTimeoutTimer = new Timer();
        if (usernameToClientId == null) { // absent from snapshots written by older versions
            usernameToClientId = new ConcurrentHashMap<>();
        }
    }

    /**
     * Attempts to set the player's icon to the given iconID and returns whether it
     * was set.
     * 
     * @param iconID the ID of the new icon to give the player.
     * @param user   the user to change the icon of.
     * @effects If no other user has the given {@code iconID}, sets the icon of the
     *          {@code user}
     *          to {@code iconID}. (exception is for the default value.)
     * @throws IllegalArgumentException if {@code user} is not in the game.
     */
    synchronized public void trySetUserIcon(String iconID, WsContext user) {
        // Verify that the user exists.
        if (!hasUser(user)) {
            throw new IllegalArgumentException("User is not in this lobby.");
        }

        String username = userToUsername.get(user);
        // Verify that no other user has the same icon. This checks everyone holding
        // a seat rather than everyone currently connected, so a player's icon is not
        // taken from under them while they are reconnecting.
        if (!iconID.equals(DEFAULT_ICON)) { // all icons other than the default cannot be shared.
            for (Entry<String, String> entry : usernameToIcon.entrySet()) {
                if (!entry.getKey().equals(username) && entry.getValue().equals(iconID)) {
                    return;
                }
            }
        }

        usernameToIcon.put(username, iconID);
        usernameToPreferredIcon.put(username, iconID);
    }

    // </editor-fold>

    ////// Game Management
    // <editor-fold desc="Game Management">

    /**
     * Returns whether the Lobby is currently in a game.
     * 
     * @return true iff the Lobby has a currently active game.
     */
    synchronized public boolean isInGame() {
        return game != null;
    }

    /**
     * Starts a new SecretHitlerGame with the connected users as players.
     * 
     * @throws StartRefusedException if there are too few or too many connected
     *                               players, if the lobby is already in a game
     *                               ({@code isInGame() == true}), or if not all
     *                               players have selected an icon.
     * @modifies this
     * @effects creates and stores a new SecretHitlerGame.
     *          The usernames of all active users are added to the game in a
     *          randomized order.
     */
    synchronized public void startNewGame() {
        pruneDeadConnections();

        // Only players who are actually connected are dealt in. A seat is held open
        // for a while after a player drops, so that a player who has really gone is
        // not dealt a role that nobody is there to play.
        List<String> humanPlayers = new ArrayList<>();
        for (String username : activeUsernames) {
            if (hasUserWithName(username)) {
                humanPlayers.add(username);
            }
        }

        if (isInGame()) {
            throw new StartRefusedException("The lobby is already in a game.");
        }
        // Every seat now belongs to a real player, so a short lobby cannot be padded
        // out. The host's client hides the button below the minimum, but a player can
        // drop between them seeing enough players and clicking, so it is checked here
        // as well -- and refused without hanging up on them.
        if (humanPlayers.size() < SecretHitlerGame.MIN_PLAYERS) {
            throw new StartRefusedException("At least " + SecretHitlerGame.MIN_PLAYERS
                    + " players are needed to start a game (" + humanPlayers.size() + " connected).");
        }
        if (humanPlayers.size() > SecretHitlerGame.MAX_PLAYERS) {
            throw new StartRefusedException("At most " + SecretHitlerGame.MAX_PLAYERS
                    + " players can play a game (" + humanPlayers.size() + " connected).");
        }

        // Check that all players have (non-default) icons set.
        for (String username : humanPlayers) {
            if (DEFAULT_ICON.equals(usernameToIcon.get(username))) {
                throw new StartRefusedException("Not all players have selected icons.");
            }
        }

        usersInGame.clear();
        usersInGame.addAll(humanPlayers);

        // Drop any seats still being held for players who did not make the roster.
        activeUsernames.retainAll(humanPlayers);

        // Initialize the new game
        List<String> playerNames = new ArrayList<>(humanPlayers);
        Collections.shuffle(playerNames);

        game = new SecretHitlerGame(playerNames);
    }

    /**
     * Returns the current game.
     * 
     * @throws RuntimeException if called when there is no active game
     *                          ({@code !this.isInGame()}).
     * @return the SecretHitlerGame for this lobby.
     */
    synchronized public SecretHitlerGame game() {
        if (game == null) {
            throw new RuntimeException();
        } else {
            return game;
        }
    }

    // </editor-fold>

}
